name: brazil_license_plate_drawing
description: Draws brazilian cars' license plate on screen.
version: 0.0.1
author: Thad Carnevalli
homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/images/brazil.png
  - assets/images/merco.png

  fonts:
  - family: Mandatory
    fonts:
      - asset: assets/fonts/mandatory.ttf
  - family: Fe
    fonts:
      - asset: assets/fonts/fe.ttf
  - family: Xanh
    fonts:
      - asset: assets/fonts/XanhMono-Regular.ttf