name: brazil_license_plate_drawing
description: Draws on the screen three different types of brazilian cars' license plates. 
version: 0.0.4
homepage: https://github.com/carnevalli/brazil_license_plate_drawing

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - packages/brazil_license_plate_drawing/assets/images/brazil.png
  - packages/brazil_license_plate_drawing/assets/images/merco.png

  fonts:
  - family: Mandatory
    fonts:
      - asset: packages/brazil_license_plate_drawing/assets/fonts/mandatory.ttf
  - family: Fe
    fonts:
      - asset: packages/brazil_license_plate_drawing/assets/fonts/fe.ttf
  - family: Xanh
    fonts:
      - asset: packages/brazil_license_plate_drawing/assets/fonts/XanhMono-Regular.ttf